name: help_repository
description: a package to crud on helps
environment:
  sdk: ^3.5.1
version: 1.0.0+1
publish_to: none
dependencies:
  base_repository:
    path: ../base_repository/
  user_repository:
    path: ../user_repository/
  network_repository:
    path: ../network_repository/