name: user_repository
description: a package to crud on users
environment:
  sdk: ^3.5.1
publish_to: none
dependencies:
  base_repository:
    path: ../base_repository/
  network_repository:
    path: ../network_repository/
  level_repository:
    path: ../level_repository/
  