name: withdraw_repository
description: a package to crud on withdraws
environment:
  sdk: ^3.5.1
publish_to: none
dependencies:
  base_repository:
    path: ../base_repository/
  network_repository:
    path: ../network_repository/
  user_repository:
    path: ../user_repository/
  