name: red_black_game_repository
description: Red Black Game Repository for handling Red Black game data and operations
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  base_repository:
    path: ../base_repository
  network_repository:
    path: ../network_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0